#:import hex kivy.utils.get_color_from_hex
MainWidget:

<MainWidget>:

    canvas.before:
        Color:
            rgba: hex('#D6EFD8')
        Rectangle:
            pos: self.pos
            size: self.size
            
    #Label:
    #    size_hint_y: 2
    #    font_size: 20
    #    text: "人狼GMアプリ"
    #    color: 0, 0, 0, 1

    BoxLayout:
        orientation: 'vertical'
        size: root.size
        spacing: 5
        padding: 5

        BoxLayout:
            size_hint_y: 2.5
            spacing: 10
            padding: 10
            canvas.before:
                Color:
                    rgba: hex('#D6EFD8')
                Rectangle:
                    size: self.size
                    pos: self.pos

            BoxLayout:
                size_hint_x: 2
                orientation: 'vertical'

                BoxLayout:
                    size_hint_y: 8
                    spacing: 10
                    padding: 10

                    #BoxLayout:
                    #    size_hint_x: 5                       
                    #    Image:
                    #        id: app_img
                    #        source: 'yupi_icon.png'

                    BoxLayout:
                        size_hint_x: 4
                        orientation: 'vertical'
                        spacing: 5
                        padding: 5

                        Button:
                            font_size: 20
                            bold: True
                            text: "参加者登録"
                            background_color: hex('#1A5319')
                            on_press: root.member_reg_popup_open()

                        Button:
                            text: '全てをリセット'
                            font_size: 20
                            background_color: hex('#1A5319')
                            on_press: root.memberResetClicked()

                        Button:
                            text: 'メンバーリセット'
                            font_size: 20
                            background_color: hex('#1A5319')
                            on_press: root.regResetClicked()

                        Button:
                            text: '内容リセット'
                            font_size: 20
                            background_color: hex('#1A5319')
                            on_press: root.gameResetClicked()

                    BoxLayout:
                        size_hint_x: 6
                        orientation: 'vertical'
                        spacing: 10
                        padding: 10
                        canvas.before:
                            Color:
                                rgba: hex('#80AF81')
                            Rectangle:
                                size: self.size
                                pos: self.pos

                        BoxLayout:
                            size_hint_y: 1
                            canvas.before:
                                Color:
                                    rgba: hex('#508D4E')
                                Rectangle:
                                    size: self.size
                                    pos: self.pos

                            Label:
                                font_size: 20
                                text: "自動配役調整"

                        BoxLayout:
                            size_hint_y: 8
                            orientation: 'vertical'
                            spacing: 5
                            padding: 5

                            BoxLayout
                                orientation: 'horizontal'

                                Label:
                                    font_size: 20
                                    text: root.POS_JINRO

                                Label:
                                    id: jinroCnt
                                    font_size: 20
                                    text: str(root.jinroCount)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "＋"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustJinroCount(1)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "ー"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustJinroCount(-1)

                            BoxLayout
                                orientation: 'horizontal'

                                Label:
                                    font_size: 20
                                    text: root.POS_KYOJIN

                                Label:
                                    id: uragiriCnt
                                    font_size: 20
                                    text: str(root.uragiriCount)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "＋"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustUragiriCount(1)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "ー"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustUragiriCount(-1)

                            BoxLayout
                                orientation: 'horizontal'

                                Label:
                                    font_size: 20
                                    text: root.POS_URANAI

                                Label:
                                    id: uranaiCnt
                                    font_size: 20
                                    text: str(root.uranaiCount)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "＋"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustUranaiCount(1)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "ー"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustUranaiCount(-1)

                            BoxLayout
                                orientation: 'horizontal'

                                Label:
                                    font_size: 20
                                    text: root.POS_REIBAI

                                Label:
                                    id: reibaiCnt
                                    font_size: 20
                                    text: str(root.reibaiCount)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "＋"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustReibaiCount(1)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "ー"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustReibaiCount(-1)

                            BoxLayout
                                orientation: 'horizontal'

                                Label:
                                    font_size: 15
                                    text: root.POS_BODYGUARD

                                Label:
                                    id: bodyguardCnt
                                    font_size: 20
                                    text: str(root.bodyguardCount)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "＋"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustBodyguardCount(1)

                                Button:
                                    font_size: 20
                                    bold: True
                                    text: "ー"
                                    background_color: hex('#1A5319')
                                    on_press: root.adjustBodyguardCount(-1)

            BoxLayout:
                size_hint_x: 5
                orientation: 'vertical'
                spacing: 10
                padding: 10
                canvas.before:
                    Color:
                        rgba: hex('#80AF81')
                    Rectangle:
                        size: self.size
                        pos: self.pos

                BoxLayout:
                    canvas.before:
                        Color:
                            rgba: hex('#508D4E')
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    Label:
                        font_size: 20
                        text: "参加者リスト（※参加者名をタップするとゲームメンバーに追加できます）"

                BoxLayout:
                    size_hint_y: 7
                    spacing: 5
                    padding: 5

                    BoxLayout:
                        orientation: 'vertical'

                        BoxLayout:
                            Label:
                                size_hint_x: 8
                                text: '名前'
                                font_size: 20

                            Label:
                                size_hint_x: 2
                                text: '削除'
                                font_size: 20

                        BoxLayout:
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[0]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)
                            
                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(0)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[1]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(1)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[2]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(2)

                        BoxLayout    
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[3]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(3)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[4]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(4)

                    BoxLayout:
                        orientation: 'vertical'

                        BoxLayout:
                            Label:
                                size_hint_x: 8
                                text: '名前'
                                font_size: 20

                            Label:
                                size_hint_x: 2
                                text: '削除'
                                font_size: 20
                    
                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[5]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(5)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[6]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(6)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[7]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(7)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[8]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(8)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[9]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(9)
                    
                    BoxLayout:
                        orientation: 'vertical'

                        BoxLayout:
                            Label:
                                size_hint_x: 8
                                text: '名前'
                                font_size: 20

                            Label:
                                size_hint_x: 2
                                text: '削除'
                                font_size: 20

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[10]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(10)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[11]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(11)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[12]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(12)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[13]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)
                                                        
                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(13)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[14]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(14)

                    BoxLayout:
                        orientation: 'vertical'

                        BoxLayout:
                            Label:
                                size_hint_x: 8
                                text: '名前'
                                font_size: 20

                            Label:
                                size_hint_x: 2
                                text: '削除'
                                font_size: 20

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[15]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(15)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[16]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(16)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[17]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(17)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[18]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(18)

                        BoxLayout
                            Button:
                                size_hint_x: 8
                                text: root.memberCaptionList[19]
                                font_size: 20
                                on_press: root.buttonMemberClicked(self.text)

                            Button:
                                size_hint_x: 2
                                text: '✕'
                                font_size: 20
                                on_press: root.memberDelete(19)

        BoxLayout:
            size_hint_y: 7.5
            spacing: 10
            padding: 10

            BoxLayout:
                size_hint_x: 2
                orientation: 'vertical'
                spacing: 5
                padding: 5
                canvas.before:
                    Color:
                        rgba: hex('#80AF81')
                    Rectangle:
                        size: self.size
                        pos: self.pos

                BoxLayout:
                    size_hint_y: 1
                    canvas.before:
                        Color:
                            rgba: hex('#508D4E')
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    Label:
                        id: regCaption
                        font_size: 20
                        text: "ゲームメンバー"

                BoxLayout:
                    Label:
                        id: regHeaderNumber
                        size_hint_x: 1
                        text: '#'
                        font_size: 20

                    Label:
                        id: regHeaderName
                        size_hint_x: 4
                        text: '名前'
                        font_size: 20

                    Label:
                        size_hint_x: 1
                        id: regHeaderDelete
                        text: '削除'
                        font_size: 20
                    
                    Label:
                        id: regHeaderPosition
                        size_hint_x: 3
                        text: '役職'
                        font_size: 20

                    Label:
                        id: regHeaderOtsuge
                        size_hint_x: 1
                        text: '告'
                        font_size: 20

                    Label:
                        size_hint_x: 1
                        text: '村'
                        font_size: 20

                BoxLayout:
                    Label:
                        id: num1
                        size_hint_x: 1
                        text: '1'
                        font_size: 20

                    Button:
                        id: reg1
                        size_hint_x: 4
                        text: root.regCaptionList[0]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '1')
                    
                    Button:
                        size_hint_x: 1
                        id: reg_delete_1
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(0)

                    Button:
                        id: position_1
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(1)

                    Button:
                        id: otsuge_1
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_1
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(1)

                BoxLayout:
                    Label:
                        id: num2
                        size_hint_x: 1
                        text: '2'
                        font_size: 20

                    Button:
                        id: reg2
                        size_hint_x: 4
                        text: root.regCaptionList[1]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '2')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_2
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(1)

                    Button:
                        id: position_2
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(2)

                    Button:
                        id: otsuge_2
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_2
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(2)

                BoxLayout:
                    Label:
                        id: num3
                        size_hint_x: 1
                        text: '3'
                        font_size: 20

                    Button:
                        id: reg3
                        size_hint_x: 4
                        text: root.regCaptionList[2]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '3')
                    
                    Button:
                        size_hint_x: 1
                        id: reg_delete_3
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(2)

                    Button:
                        id: position_3
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(3)

                    Button:
                        id: otsuge_3
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_3
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(3)

                BoxLayout:
                    Label:
                        id: num4
                        size_hint_x: 1
                        text: '4'
                        font_size: 20

                    Button:
                        id: reg4
                        size_hint_x: 4
                        text: root.regCaptionList[3]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '4')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_4
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(3)

                    Button:
                        id: position_4
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(4)

                    Button:
                        id: otsuge_4
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_4
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(4)

                BoxLayout:
                    Label:
                        id: num5
                        size_hint_x: 1
                        text: '5'
                        font_size: 20

                    Button:
                        id: reg5
                        size_hint_x: 4
                        text: root.regCaptionList[4]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '5')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_5
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(4)

                    Button:
                        id: position_5
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(5)

                    Button:
                        id: otsuge_5
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_5
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(5)

                BoxLayout:
                    Label:
                        id: num6
                        size_hint_x: 1
                        text: '6'
                        font_size: 20

                    Button:
                        id: reg6
                        size_hint_x: 4
                        text: root.regCaptionList[5]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '6')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_6
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(5)

                    Button:
                        id: position_6
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(6)

                    Button:
                        id: otsuge_6
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_6
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(6)

                BoxLayout:
                    Label:
                        id: num7
                        size_hint_x: 1
                        text: '7'
                        font_size: 20

                    Button:
                        id: reg7
                        size_hint_x: 4
                        text: root.regCaptionList[6]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '7')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_7
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(6)

                    Button:
                        id: position_7
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(7)

                    Button:
                        id: otsuge_7
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_7
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(7)

                BoxLayout:
                    Label:
                        id: num8
                        size_hint_x: 1
                        text: '8'
                        font_size: 20

                    Button:
                        id: reg8
                        size_hint_x: 4
                        text: root.regCaptionList[7]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '8')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_8
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(7)

                    Button:
                        id: position_8
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(8)

                    Button:
                        id: otsuge_8
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_8
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(8)

                BoxLayout:
                    Label:
                        id: num9
                        size_hint_x: 1
                        text: '9'
                        font_size: 20

                    Button:
                        id: reg9
                        size_hint_x: 4
                        text: root.regCaptionList[8]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '9')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_9
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(8)

                    Button:
                        id: position_9
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(9)

                    Button:
                        id: otsuge_9
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_9
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(9)

                BoxLayout:
                    Label:
                        id: num10
                        size_hint_x: 1
                        text: '10'
                        font_size: 20

                    Button:
                        id: reg10
                        size_hint_x: 4
                        text: root.regCaptionList[9]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '10')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_10
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(9)

                    Button:
                        id: position_10
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(10)

                    Button:
                        id: otsuge_10
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_10
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(10)
                
                BoxLayout:
                    Label:
                        id: num11
                        size_hint_x: 1
                        text: '11'
                        font_size: 20

                    Button:
                        id: reg11
                        size_hint_x: 4
                        text: root.regCaptionList[10]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '11')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_11
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(10)

                    Button:
                        id: position_11
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(11)

                    Button:
                        id: otsuge_11
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_11
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(11)
                    
                BoxLayout:
                    Label:
                        id: num12
                        size_hint_x: 1
                        text: '12'
                        font_size: 20

                    Button:
                        id: reg12
                        size_hint_x: 4
                        text: root.regCaptionList[11]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '12')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_12
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(11)

                    Button:
                        id: position_12
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(12)

                    Button:
                        id: otsuge_12
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_12
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(12)
                
                BoxLayout:
                    Label:
                        id: num13
                        size_hint_x: 1
                        text: '13'
                        font_size: 20

                    Button:
                        id: reg13
                        size_hint_x: 4
                        text: root.regCaptionList[12]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '13')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_13
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(12)

                    Button:
                        id: position_13
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(13)

                    Button:
                        id: otsuge_13
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_13
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(13)

                BoxLayout:
                    Label:
                        id: num14
                        size_hint_x: 1
                        text: '14'
                        font_size: 20

                    Button:
                        id: reg14
                        size_hint_x: 4
                        text: root.regCaptionList[13]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '14')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_14
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(13)

                    Button:
                        id: position_14
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(14)

                    Button:
                        id: otsuge_14
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_14
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(14)

                BoxLayout:
                    Label:
                        id: num15
                        size_hint_x: 1
                        text: '15'
                        font_size: 20

                    Button:
                        id: reg15
                        size_hint_x: 4
                        text: root.regCaptionList[14]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '15')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_15
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(14)

                    Button:
                        id: position_15
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(15)

                    Button:
                        id: otsuge_15
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_15
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(15)

                BoxLayout:
                    Label:
                        id: num16
                        size_hint_x: 1
                        text: '16'
                        font_size: 20

                    Button:
                        id: reg16
                        size_hint_x: 4
                        text: root.regCaptionList[15]
                        font_size: 20
                        on_press: root.membar_name_popup_open(self.text, '16')

                    Button:
                        size_hint_x: 1
                        id: reg_delete_16
                        text: '✕'
                        font_size: 20
                        on_press: root.regDelete(15)

                    Button:
                        id: position_16
                        size_hint_x: 3
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.position_popup_open(16)

                    Button:
                        id: otsuge_16
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press:
                            if self.text == '': self.text = '◯';
                            elif self.text == '◯': self.text = ''

                    Button:
                        id: muracnt_16
                        size_hint_x: 1
                        text: ''
                        font_size: 20
                        disabled_color:　(1, 1, 1, 1)
                        on_press: root.adjustMuraCount(16)

                BoxLayout
                    Button:
                        size_hint_x: 3
                        text: "配役"
                        font_size: 20
                        background_color: hex('#1A5319')
                        on_press: root.autoPositionClicked()

                    Button:
                        size_hint_x: 3
                        text: "お告げ"
                        font_size: 20
                        background_color: hex('#1A5319')
                        on_press: root.autoSetting()
                
                    Button:
                        size_hint_x: 4
                        id: game_start_btn
                        text: "ゲーム開始"
                        font_size: 20
                        background_color: hex('#1A5319')
                        on_press: root.game_start()

            BoxLayout
                orientation: 'vertical'
                size_hint_x: 7
                spacing: 5
                padding: 5
                canvas.before:
                    Color:
                        rgba: hex('#80AF81')
                    Rectangle:
                        size: self.size
                        pos: self.pos

                BoxLayout
                    size_hint_y: 0.5
                    canvas.before:
                        Color:
                            rgba: hex('#508D4E')
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    Label:
                        id: regCaption
                        font_size: 20
                        text: "ゲーム進行状況"

                BoxLayout
                    size_hint_y: 9.5

                    BoxLayout:
                        id: day1_result
                        size_hint_y: 1
                        size_hint_x: 0.6
                        orientation: 'vertical'

                    BoxLayout:
                        id: day2_result
                        size_hint_x: 0.6
                        orientation: 'vertical'

                    BoxLayout:
                        id: day3_result
                        size_hint_x: 0.6
                        orientation: 'vertical'

                    BoxLayout:
                        id: day4_result
                        size_hint_x: 0.6
                        orientation: 'vertical'

                    BoxLayout:
                        id: day5_result
                        size_hint_x: 0.6
                        orientation: 'vertical'    

                    BoxLayout:
                        id: day6_result
                        size_hint_x: 0.6
                        orientation: 'vertical'

                    BoxLayout:
                        id: day7_result
                        size_hint_x: 0.6
                        orientation: 'vertical'         